version: "3"
services:

    nodejs:
        container_name: nodejs
        hostname: nodejs
        image: nodejs
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 8001
        links:
            - mongodb
            - redis


    nginx:
        container_name: nginx
        hostname: nginx
        image: nginx
        links:
            - "nodejs:nodejs"
        volumes:
            - ./nginx-conf:/etc/nginx/conf.d

        depends_on:
            - nodejs


    redis:
        image: redis
        container_name: redis
        command: ["redis-server", "--bind", "redis", "--port", "6379"]
        hostname: redis
        expose:
            - 6379
        logging:
            driver: none


    

    mongodb:
        container_name: mongodb
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27018:27017"
        logging:
            driver: none
